version: '3.3'
services:
  db:
    image: postgres:9.5
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: master
      POSTGRES_DB: maiorNota
    ports:
      - "5432:5432"
